# 01 - Importation, Audit et Nettoyage des Données (Couche Silver)

Ce notebook a pour objectif de :
1. Charger les sources de données brutes (Bronze).
2. Auditer la qualité des données (valeurs manquantes, doublons, types).
3. Nettoyer et transformer les données pour créer une base fiable (Silver).
4. Exporter le fichier propre qui servira pour toutes nos analyses futures.

In [2]:
# Importation des bibliothèques nécessaires
import pandas as pd
import numpy as np

print("Bibliothèque importées avec succès")

Bibliothèque importées avec succès

## 1. Ingestion des données brutes
Nous chargeons ici nos fichiers sources.

In [3]:
Sales = pd.read_csv("Sales _bronze_silver.csv")
print("Fichier importé avec sucès")

Fichier importé avec sucès

## 2.1. Aperçu visuel des premières lignes (head)

In [4]:
print("En tête du tableau Sales :\n")
display(Sales.head())

En tête du tableau Sales :

,OrderID,CustomerID,CompanyName,ProductID,ProductName,Category,RegionID,RegionName,OrderDate,Quantity,UnitPrice,TotalPrice,OrderStatus
0,ORD-0001,C005,AI Systems,P002,Smartphone,Electronics,R004,West,2023-05-18,1,1344,1344,Delivered
1,ORD-0001,C005,AI Systems,P004,Monitor,Electronics,R004,West,2023-05-18,1,390,390,Delivered
2,ORD-0001,C005,AI Systems,P005,Keyboard,Accessories,R004,West,2023-05-18,4,1140,4560,Delivered
3,ORD-0002,C001,TechCorp,P003,Tablet,Electronics,R001,North,2023-07-30,1,200,200,Shipped
4,ORD-0002,C001,TechCorp,P006,Mouse,Accessories,R001,North,2023-07-30,2,1105,2210,Shipped

## 2.2. Vérification de la forme du jeu de données (shape)

In [5]:
print("Forme du tableau :")
display(Sales.shape)

Forme du tableau :

(1043, 13)

## 2.3. Analyse de la structure et des types de données (info)

In [6]:
print("Infos essentielles du tableau")
display(Sales.info())

Infos essentielles du tableau
<class 'pandas.DataFrame'>
RangeIndex: 1043 entries, 0 to 1042
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   OrderID      1043 non-null   str
 1   CustomerID   1043 non-null   str
 2   CompanyName  1043 non-null   str
 3   ProductID    1043 non-null   str
 4   ProductName  1043 non-null   str
 5   Category     1043 non-null   str
 6   RegionID     1043 non-null   str
 7   RegionName   1043 non-null   str
 8   OrderDate    1043 non-null   str
 9   Quantity     1043 non-null   int64
 10  UnitPrice    1043 non-null   int64
 11  TotalPrice   1043 non-null   int64
 12  OrderStatus  1043 non-null   str
dtypes: int64(3), str(10)
memory usage: 106.1 KB

None

In [7]:
print("Resume statistique : \n")
display(Sales.describe())

Resume statistique :

          Quantity    UnitPrice   TotalPrice
count  1043.000000  1043.000000  1043.000000
mean      2.980825   776.570470  2299.108341
std       1.404550   415.474688  1740.714184
min       1.000000    50.000000    55.000000
25%       2.000000   423.500000   921.000000
50%       3.000000   767.000000  1810.000000
75%       4.000000  1124.000000  3352.500000
max       5.000000  1496.000000  7470.000000

## 2.5. Détection précise des valeurs manquantes (isnull().sum)

In [8]:
print("Analyse détaillée des valeurs manquantes :\n")

valeurs_manquantes = pd.DataFrame({
    "Valeurs manquantes": Sales.isnull().sum(),
    "Pourcentage %": (Sales.isnull().sum() / len(Sales)) * 100
})

display(valeurs_manquantes)

Analyse détaillée des valeurs manquantes :

             Valeurs manquantes  Pourcentage %
OrderID                       0            0.0
CustomerID                    0            0.0
CompanyName                   0            0.0
ProductID                     0            0.0
ProductName                   0            0.0
Category                      0            0.0
RegionID                      0            0.0
RegionName                    0            0.0
OrderDate                     0            0.0
Quantity                      0            0.0
UnitPrice                     0            0.0
TotalPrice                    0            0.0
OrderStatus                   0            0.0

## 2.6. Recherche des lignes dupliquées (duplicated().sum)

In [9]:
print("Analyse des doublons :\n")

nb_doublons = Sales.duplicated().sum()
pourcentage_doublons = (nb_doublons / len(Sales)) * 100

print(f"Nombre de lignes dupliquées : {nb_doublons}")
print(f"Pourcentage de doublons : {pourcentage_doublons:.2f}%")

Analyse des doublons :

Nombre de lignes dupliquées : 0
Pourcentage de doublons : 0.00%

## 2.7. Analyse de la répartition des catégories (value_counts)

In [10]:
print("Répartition des ventes par entreprise (CompanyName) :\n")
display(Sales["CompanyName"].value_counts())

print("\nRépartition des ventes par région (RegionName) :\n")
display(Sales["RegionName"].value_counts())

print("\nRépartition des ventes par produit (ProductName) :\n")
display(Sales["ProductName"].value_counts())

Répartition des ventes par entreprise (CompanyName) :

CompanyName
CyberSecure           142
TechCorp              141
GreenTech             141
AI Systems            139
DataWorks             125
NextGen Consulting    123
InnovaSolutions       117
CloudNet              115
Name: count, dtype: int64

Répartition des ventes par région (RegionName) :

RegionName
South    297
West     268
North    242
East     236
Name: count, dtype: int64

Répartition des ventes par produit (ProductName) :

ProductName
Smartphone    138
Tablet        137
Keyboard      135
Smartwatch    135
Headphones    131
Laptop        127
Mouse         125
Monitor       115
Name: count, dtype: int64

In [11]:
print("Colonnes textuelles (object) :\n")
display(Sales.select_dtypes(include=['object']).head())
print("\nColonnes numériques (number) :\n")
display(Sales.select_dtypes(include=['number']).head())

Colonnes textuelles (object) :

C:\Users\mboum\AppData\Local\Temp\ipykernel_21508\1027957236.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(Sales.select_dtypes(include=['object']).head())

,OrderID,CustomerID,CompanyName,ProductID,ProductName,Category,RegionID,RegionName,OrderDate,OrderStatus
0,ORD-0001,C005,AI Systems,P002,Smartphone,Electronics,R004,West,2023-05-18,Delivered
1,ORD-0001,C005,AI Systems,P004,Monitor,Electronics,R004,West,2023-05-18,Delivered
2,ORD-0001,C005,AI Systems,P005,Keyboard,Accessories,R004,West,2023-05-18,Delivered
3,ORD-0002,C001,TechCorp,P003,Tablet,Electronics,R001,North,2023-07-30,Shipped
4,ORD-0002,C001,TechCorp,P006,Mouse,Accessories,R001,North,2023-07-30,Shipped

Colonnes numériques (number) :

   Quantity  UnitPrice  TotalPrice
0         1       1344        1344
1         1        390         390
2         4       1140        4560
3         1        200         200
4         2       1105        2210

## 3. Nettoyage des données
### 3.1. Nettoyage des colonnes textuelles

L'objectif de cette étape est d'éliminer le "bruit" invisible dans les colonnes de type `object` :
- Suppression des espaces superflus au début et à la fin (`.str.strip()`).
- Choix de conserver la casse d'origine (pas de `.str.lower()`), les libellés étant déjà propres et professionnels pour un rapport B2B.

In [12]:
# Sélectionne toutes les colonnes textuelles
colonnes_texte = Sales.select_dtypes(include=["object"]).columns
# Applique le strip() sur chacune d'elles
for cols in colonnes_texte:
    Sales[cols] = Sales[cols].str.strip()
print("Espace avant et après supprimés avec succès")

Espace avant et après supprimés avec succès

C:\Users\mboum\AppData\Local\Temp\ipykernel_21508\3965397146.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  colonnes_texte = Sales.select_dtypes(include=["object"]).columns

### 3.2. Conversion et enrichissement de la date de commande (`OrderDate`)

- **Conversion** : Passage du format texte au format `datetime` de Pandas pour permettre les tris et analyses chronologiques.
- **Enrichissement (Feature Engineering)** : Extraction de nouvelles colonnes clés pour le reporting (Année, Mois, Trimestre, etc.).

In [13]:
# Conversion de la colonne OrderDate au format datetime
Sales["OrderDate"] = pd.to_datetime(Sales["OrderDate"])
print("Date convertie au format Date")

Date convertie au format Date

In [14]:
print("Extraction de l'année...")
Sales["OrderYear"] =  Sales["OrderDate"].dt.year

print("Extraction du mois...")
Sales["OrderMonth"] = Sales["OrderDate"].dt.month

print("Extraction du trimestre...")
Sales["OrderQuarter"] = Sales["OrderDate"].dt.quarter

print("Enrichissement temporel terminé avec succès !")

Extraction de l'année...
Extraction du mois...
Extraction du trimestre...
Enrichissement temporel terminé avec succès !

In [15]:
# Vérification rapide des dates
print("Valeurs manquantes dans OrderDate :", Sales["OrderDate"].isnull().sum())
print("Période couverte : du", Sales["OrderDate"].min(), "au", Sales["OrderDate"].max())

Valeurs manquantes dans OrderDate : 0
Période couverte : du 2023-01-03 00:00:00 au 2023-12-30 00:00:00

### 3.3. Vérification des colonnes numériques
- Les types (`int`) et les plages de valeurs ont été audités lors de l'EDA. 
- Aucune anomalie (valeurs négatives ou aberrantes) détectée, aucune transformation nécessaire sur cette partie.

In [16]:
# vérification des limites sur une colonne de quantité
# On cherche les lignes qui violent la règle (quantité <= 0 ou quantité > 25)
anomalies_quantity = Sales[(Sales["Quantity"] < 0) | (Sales["Quantity"] > 25)]
print(f"Nombre d'anomalies détectées sur les quantités : {len(anomalies_quantity)}")

# Si besoin d'afficher ces lignes pour les inspecter :
if len(anomalies_quantity) > 0:
    display(anomalies_quantity)
else:
    print("Toutes les quantités respectent les règles métiers.")

Nombre d'anomalies détectées sur les quantités : 0
Toutes les quantités respectent les règles métiers.

In [ ]:
# vérification des limites sur une colonne de quantité
# On cherche les lignes qui violent la règle (quantité <= 100 ou quantité > 10000)
anomalies_UnitPrice = Sales[(Sales["UnitPrice"] <= 20) |  (Sales["UnitPrice"] > 10000)]
print(f"Nombre d'anomalies détectées sur les UnitPrice : {len(anomalies_UnitPrice)}")

if len(anomalies_UnitPrice) > 0:
    display(anomalies_UnitPrice)
else: print("Tous les UnitPrice respectent les règles métiers.")

ombre d'anomalies détectées sur les UnitPrice : 0
Tous les UnitPrice respectent les règles métiers.